### ISSUE TITLE
can i contribute

### ISSUE THREAD

**Issue by keenanyafiqy** [thebigcrafter/AdvancedPluginManager#16]
can i make my own language?

**Comment by MintoD** [comment]
Yes, you can. Following this [contributing guide](https://github.com/thebigcrafter/AdvancedPluginManager/blob/main/CONTRIBUTING.md) to translate this plugin

**Comment by MintoD** [comment]
If you have some problems while translating this plugin, please join our [Discord](https://discord.gg/xfTeF6aMhp)server and we will help you.
