### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by keenanyafiqy** [thebigcrafter/AdvancedPluginManager#21]
How this PLUGIN works?

**Comment by MintoD** [comment]
Unlike Sheep install plugins from Poggit. This plugin installed the plugin from the repository. I'm writing a document for it. If you need something like Sheep, you can check out this plugin [oh-my-pmmp](https://github.com/MintoD/oh-my-pmmp)

**Comment by keenanyafiqy** [comment]
Oh so that's the usage

**Comment by keenanyafiqy** [comment]
So it's like a ServerTools plugin,
But different?
