### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by DimonYoing** [thebigcrafter/AdvancedPluginManager#23]
Can you explain what exactly this plugin does, I don't understand how to use plugins to do?

**Comment by NhanAZ** [comment]
Please see this issue https://github.com/thebigcrafter/AdvancedPluginManager/issues/21

**Comment by DimonYoing** [comment]
I looked, but I still didn't understand what yes how tI looked, but I still didn't understand what was going on there

**Comment by keenanyafiqy** [comment]
See this issue: #6 
If you still don't understand
